name = "ace-api-frequency-test"
main = "../test-ace-api-frequency.js"
compatibility_date = "2024-01-01"

[env.production]

[env.production.vars]
ACE_API_BASE = "https://flightdeck.aceiot.cloud/api"

# Set secrets with:
# wrangler secret put ACE_API_KEY -c workers/wrangler-ace-test.toml --env production
