name: Seed Configured Points (Auto-Discovery)

on:
  workflow_dispatch:
    inputs:
      site:
        description: "Site name (e.g., ses_falls_city)"
        required: true
        default: "ses_falls_city"
  schedule:
    # Run daily at 1 AM to discover new points
    - cron: '0 1 * * *'

permissions:
  contents: read

jobs:
  seed:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      ACE_API_KEY: ${{ secrets.ACE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/python/requirements.txt

      - name: Seed configured points for ses_falls_city
        run: |
          python scripts/python/seed_configured_points.py --site ses_falls_city

      - name: Summary
        run: |
          echo "## Configured Points Seeded" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Seeded all configured points from ACE API into Supabase." >> $GITHUB_STEP_SUMMARY
          echo "This ensures backfills and sync get data for ALL points, not just existing ones." >> $GITHUB_STEP_SUMMARY
